# Generated by Django 4.0.3 on 2022-05-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('photo', models.ImageField(default='books/default_book.png', null=True, upload_to='books/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'list of categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('body', models.TextField()),
                ('post_time_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'list of reviews',
                'ordering': ['post_time_created'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50, null=True)),
                ('pageCount', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(default='books/default_book.png', null=True, upload_to='books/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
            options={
                'verbose_name': 'list of books',
                'ordering': ['title', 'id'],
            },
        ),
    ]
