# Generated by Django 4.0.3 on 2022-04-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pageCount', models.IntegerField(null=True)),
                ('photo', models.ImageField(default='book-photo.svg', null=True, upload_to='')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('body', models.TextField()),
                ('post_time_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
