# Generated by Django 4.0.3 on 2022-04-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'id'], 'verbose_name': 'list of books'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'list of categories'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['post_time_created'], 'verbose_name': 'list of reviews'},
        ),
    ]
