# Generated by Django 4.0.3 on 2022-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='books/default_book.png', null=True, upload_to='books/%Y/%m/%d/'),
        ),
    ]
