# Generated by Django 4.0.3 on 2022-04-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='books/default_book.png', null=True, upload_to='books/%Y/%m/%d/'),
        ),
    ]
